### ISSUE TITLE
опечатка в задаче в параграфе "Углы"

### ISSUE THREAD

**Issue by lostpeaceofchalk** [anton-petrunin/kiselyov-2D#18]
в файле `2D/ugly.tex` (и на странице 19 PDF-файла с arxiv.org соответственно) есть задача 6, в этой задаче написано, что углы **AOB** и BOC равны, но при взгляде на рисунок к задаче, очевидно, что это не так.
Интернет эту задачу знает, но равными называются углы **AOD** и BOC.

**Comment by anton-petrunin** [comment]
Спасибо, вот исправил: https://github.com/anton-petrunin/kiselyov/commit/8f75eabc0dcb7aa95f50783aa781723188dec64a
